dbt_learn_repos: 
  outputs:
    dev:
      account: MKZRIYN-PW92427
      database: DEV
      password: 'dbtPassword123'
      role: TRANSFORM
      schema: BRONZE_AIRBNB
      threads: 1
      type: snowflake
      user: dbt
      warehouse: COMPUTE_WH
    uat:
        account: MKZRIYN-PW92427
        database: uat
        password: '8L$%WTfaNf2#4Y'
        role: ACCOUNTADMIN
        schema: BRONZE_AIRBNB
        threads: 1
        type: snowflake
        user: DINGINESS
        warehouse: COMPUTE_WH
  target: dev
